#https://dev.to/mastersam07/configuring-travis-ci-and-coveralls-with-flutter-2b29
language: dart
dist: trusty
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache